### ISSUE TITLE
Nefunguje mi migracia s usermi

### ISSUE THREAD

**Issue by patizon** [mp205/secmon_backend#11]
ked dam do prazdnej databazky migrovat verziu s usermi tak to pri druhej migracii pada na 68 riadku. Vraj uz idx_role_id existuje.

**Comment by mp205** [comment]
In PostgreSQL, there cannot be multiple indices with same name, even across tables.
Problem was that tables `rel_user_role` and `rel_role_permissions` both had index with name `idx_role_id`.
Fixed by renaming indices using same style as with foreign keys.
